### ISSUE TITLE
First command from installation instructions fail

### ISSUE THREAD

**Issue by raulferras** [Rydra/bgm-for-es#1]
I'm trying to install your script but the very first command fail to run:

```shell
sudo echo "deb [trusted=yes] https://repo.fury.io/rydra/ /" > /etc/apt/sources.list.d/es-bgm.list
```

It is complaining about:
```shell
-bash: /etc/apt/sources.list.d/es-bgm.list: Permission denied
```

I had to manually edit the file with:

```shell
sudo vi /etc/apt/sources.list.d/es-bgm.list
```

And add the line 
`deb [trusted=yes] https://repo.fury.io/rydra/ /`

into the file

**Comment by Rydra** [comment]
It does not seem to have anything to do with the package, though try to use the command the following way:

```
sudo "echo 'deb [trusted=yes] https://repo.fury.io/rydra/ /'" > /etc/apt/sources.list.d/es-bgm.list
```

If still it doesn't work, open the file `/etc/apt/sources.list.d/es-bgm.list` with your favourite editor (I use nano) and add the following line to the file. Afterwards, save it and follow the rest of the instructions:

`deb [trusted=yes] https://repo.fury.io/rydra/ /'`
