### ISSUE TITLE
Repository's Dead

### ISSUE THREAD

**Issue by cow-killer** [Rydra/bgm-for-es#10]
So I can't install the script on my Odroid Go Advance.

**Comment by lancer1977** [comment]
I had to jump through a few hoops but you can still install this from the source. I had to run a few prerequisites first
add /home/pi/.local/bin to my PATH (command for me was export PATH="/home/pi/.local/bin:$PATH" )
sudo apt-get install python3-stdeb
pip install wheel
pip install git+https://github.com/lancer1977/bgm-for-es

FYI I forked this repo and added another item for daphne, there are probably more needed. Repo is dead as I did a PR for this change over a year ago with no response. Feel free to fork mine and update with your own requirements. Only issue is I am not certain how easy this is to maintain. There IS also a "make debian-package" you can run from source, but I haven't tried this path yet as it was having issues for me.

**Comment by Rydra** [comment]
@cow-killer the script was developed and tested for a Raspberry pi 3B. Feel free to make pull requests if you find a way to provide support for your device.

**Comment by askotx** [comment]
@lancer1977 could lend me a hand?

I've tried this on RPi 3B -still reliable- with retropie 4.6:

```
export PATH="/home/pi/.local/bin:$PATH"
sudo apt-get update
sudo apt-get install python3-pip
sudo apt-get install python-stdeb
sudo apt-get install python-pygame
pip install wheel
pip install git+https://github.com/lancer1977/bgm-for-es
```
I've also used pip3 and python3-*, what else do I need to use bgm, rebooted and nothing, any help please?

**Comment by lancer1977** [comment]
@askotx looks like the original authors code is back up and running, I just used it today to setup a intel x86 retropie box.

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
Feedback always appreciated!
