### ISSUE TITLE
Music doesn't stop with non-RA cores

### ISSUE THREAD

**Issue by robbalvey** [Rydra/bgm-for-es#11]
I love this script but anytime I run a non-Retroarch core, like Daphne or MESS the music just keeps playing. Is there any way to stop the music when these cores load up?

**Comment by bealebe** [comment]
We just need to add the emulator name to the list that is in `MusicStateMachine.py`. 

Mine does it on the `drastic` emulator for DS... I'm not very linux savvy or github savvy or else I would fork my own version and build it locally with all the emulator names I use.

**Comment by LordShadow505** [comment]
Where is the location of MusicStateMachine.py?

**Comment by robbalvey** [comment]
/usr/lib/python2.7/dist-packages/bgm/

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
The new config file now allows you to update/customize the processes and emulators where the music should stop, without having to fiddle with code. Feedback always appreciated!
