### ISSUE TITLE
Most files play at a lower speed and pitch

### ISSUE THREAD

**Issue by jross200** [Rydra/bgm-for-es#12]
Been working for hours trying different files,bit rates, etc.  Nothing fixes it.  Everything seems to play at what I would say is 70% speed and pitch.

**Comment by jross200** [comment]
update

wiped and reloaded the pi4, reinstalled everything.  Now files play at... maybe 25% speed and pitch.  Basically just worse.

**Comment by Rydra** [comment]
Hi @jross200, unfortunately I don't have a Pi4 to test the behaviour of this script. Any pull request fixing this will be welcome :)

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
Feedback always appreciated!
