### ISSUE TITLE
Background music does not play on Retropie 4.7.1 on Raspberry pi 4

### ISSUE THREAD

**Issue by V1C3-V3RS4** [Rydra/bgm-for-es#13]
Everything installs properly with no errors but the background music doesnt actually play on the main menu.

**Comment by Rydra** [comment]
Hi @V1C3-V3RS4 . Unfortunately I don't have a Raspberry pi 4 to try and test, so if there's anyone that wants to make a pull request to try it I will much appreciate :)

**Comment by V1C3-V3RS4** [comment]
> Hi @V1C3-V3RS4 . Unfortunately I don't have a Raspberry pi 4 to try and test, so if there's anyone that wants to make a pull request that fixes this I will much appreciate it :)

Do you know what the recommended audio settings in emulationstation are to make it play from hdmi? I can hear the navigation and video sounds so i know its working, but theres so many driver options etc. To choose from

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
Feedback always appreciated!
