### ISSUE TITLE
Unable to open SDL audio: ALSA Device or resource busy

### ISSUE THREAD

**Issue by robbalvey** [Rydra/bgm-for-es#14]
I've installed this on the GPi Case 2 using a CM4 board and I get the following error:

AudioManager Error - Unable to open SDL audio: ALSA: Couldn't open audio device: Device or resource busy.

The BGM music plays just fine, but the emulationstation navigational sounds no longer play. Any ideas what I could do to fix this?

NOTE: I have this script up and running just fine on my Pi 4 so I have been able to get it functional just fine on another device.  Thank you.

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
Feedback always appreciated!

**Comment by StonedEdge** [comment]
Currently experiencing the same issue on my end.

**Comment by mrobss** [comment]
I am getting the exact same issue on the Pi 5 as reported in this error.  Was there ever a solution for this?
