### ISSUE TITLE
Clean Install Fails on Ubuntu 20.04.4 LTS / Tinkerboard / Python 3.8.10 / 

### ISSUE THREAD

**Issue by 2play** [Rydra/bgm-for-es#16]
System & Installed SW:
**Ubuntu 20.04.4 LTS / Tinkerboard / Python 3.8.10** 

Fixed my side. Ignore issue.

**Comment by 2play** [comment]
im closing as

**Comment by robbalvey** [comment]
What did you do to fix it?  I'm having the same issue and so far have not found a solution.

**Comment by robbalvey** [comment]
What did you do to fix it?  I'm having the same issue and have not yet found a solution.

**Comment by 2play** [comment]
Can't recall what the problem was and have made some changes on my fork.
You can download my vanilla base which has it installed

Just make sure you have all needed libs installed required by the esbgm
