### ISSUE TITLE
Can't remove  python-es-bgm

### ISSUE THREAD

**Issue by danyboy666** [Rydra/bgm-for-es#2]
And I can,t force the installation either I think the pkg was corrupted somehow while installting the first time.

 ```
sudo apt install -f python-pygame python-es-bgm
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pygame is already the newest version (1.9.1release+dfsg-10).
python-es-bgm is already the newest version (1.0.1-1).
0 upgraded, 0 newly installed, 0 to remove and 47 not upgraded.
1 not fully installed or removed.
Need to get 0 B/5,836 B of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: error processing package python-es-bgm (--configure):
 package python-es-bgm is not ready for configuration
 cannot configure (current status 'half-installed')
Errors were encountered while processing:
 python-es-bgm
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I need to remove this package since it doesn't work on my ubuntu install.

Edit: nevermind i've managed to clean my system.

**Comment by SirMcFrosty** [comment]
hi @Rydra i have the same problem as @danyboy666 none of the know common solutions to solve such worked out. more specific informaiton for the python-es-bgm is not to find on the net for real.

(i deleted afterwards manually as much files from your script as i could find trough looking into your setup script. cleaned source-list too. did not help to reinstall nor to remove with apt... always same error)

please help as that stupid error disturbs any installation on various other packages/scripts. driving me nuts and i dont want to begin new with all configurations and so on on my new retropie image i made.

thanks in advance

**Comment by danyboy666** [comment]
Use apt-install instead of apt, force reinstall after that you can purge the package if i recall the steps I did. For some reason apt remove isnt working



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by SirMcFrosty** [comment]
I tried already 
sudo apt-get install --reinstall python-es-bgm 
and variations. more or less i still get the same error message which states that package python-es-bgm (--remove) gave back an error in sub-process of post-removal-Script
last line additional to above: E: Sub-process /usr/bin/dpkg returned an error code (1)

meanwhile i have no clue what else i can try. and that message repeats even when i install something else in retropie stretch.

**Comment by atrumcorvus** [comment]
**Fallowing packages removed**
sudo apt remove python-setuptools python-pkg-resources python-es-bgm

errorcode follows

**then**
ls /var/lib/dpkg/info | grep -i 'python-es-bgm'
python-es-bgm.conffiles
python-es-bgm.list
python-es-bgm.md5sums
python-es-bgm.postinst
python-es-bgm.postrm
python-es-bgm.prerm

sudo rm -rf /etc/bgmconfig.txt /usr/bin/bgmstart /var/lib/dpkg/info/python-es-bgm.list /var/lib/dpkg/info/python-es-bgm.conffiles /var/lib/dpkg/info/python-es-bgm.md5sums /var/lib/dpkg/info/python-es-bgm.postinst /var/lib/dpkg/info/python-es-bgm.postrm /var/lib/dpkg/info/python-es-bgm.prerm

sudo apt update; sudo apt full-upgrade

bingo
have a nice day
