### ISSUE TITLE
Volume control?

### ISSUE THREAD

**Issue by nikkoman** [Rydra/bgm-for-es#4]
Where is the script itself located? I would like to be able to tweak more settings with the most important one being volume.

**Comment by alan2022000** [comment]
Same here if anyone can help. 

I know I need to edit MusicPlayer.py for volume as by default it’s to low. But where is it?

**Comment by Red-K** [comment]
Hey.

Thanks for the info on where to find the script :) I noticed that when starting a game, the music continues to play for a good few seconds before fading. Changing the fade speed makes it fade faster/slower, but the music plays for too long before it actually starts to fade. Do you know if you can make the music stop sooner? I've had a look in the script but not really sure what to adjust.

Thanks

**Comment by alan2022000** [comment]
Would love to help you there but I didn’t experience that problem. 
This does tho lead me to believe that maybe you got something else going on causing the fade out part to start later than it should. So not related to this script in particular.

**Comment by Red-K** [comment]
Hmmm, okay. Really no idea where to start as not too good with Linux lol.

**Comment by alan2022000** [comment]
Same here. One thing I have learned is either burning the same image again to your SD card or use a different one or version. I ended up using motionblue v6. I did try v7 recently but found issues with the background audio on that image so went back to v6. What’s helpful is this image of Retropie has the audio script pre installed on the image so didn’t have mess with any settings.

**Comment by Red-K** [comment]
Thanks a lot 😊 Will try it.

Last thing, I don’t suppose you know how to change the length of a launching image. When you start a game you can place an image called “launching.jpg” to display but it only stays on screen for a couple of seconds.

Sent from Mail for Windows 10

**Comment by alan2022000** [comment]
If you google it I’m sure there might be a way. But I just thought of a quick and simple way to cheat that. Just make a mp4 video of the picture and make the video how ever long you want it to stay on screen on start up.

**Comment by Red-K** [comment]
Hi. Thanks so much for your quick reply. Just found its in run command 😁
Thanks again

**Comment by alan2022000** [comment]
Glad you found the setting. I’ve never used an image. I’ve always used a video so I just  picked a longer video.
