### ISSUE TITLE
BGM making Pi run slowly

### ISSUE THREAD

**Issue by Fanman03** [Rydra/bgm-for-es#5]
This program makes my RasPi 1 run really slowly in MAME ROMs and makes the ROM audio run really slowly. Any known fix for this?

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
Feedback always appreciated!
