### ISSUE TITLE
BGM Not Stopping with Open BOR

### ISSUE THREAD

**Issue by LinkToTheAsh** [Rydra/bgm-for-es#9]
Hi @Rydra 

Your script is awesome and works great in mysetup with everything but Open BOR, where in the script would I add the ability to pause the music when open BOR is running?

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
The new config file allows you to configure custom processes where the music should stop, without having to fiddle with code. Feedback always appreciated!
